Update Checker
overtools/OWLib pull request #124
Opened 2021-04-03 11:44 UTC by prophetl33t

2021-04-03 13:40 UTC, Js41637 requested changes

2021-04-03 13:40 UTC, Js41637 commented on DataTool/ToolFlags.cs
> +        [CLIFlag(Default = false, Flag = "disable-upd-chk", Help = "Disables datatool update check (happens if CASC init fails)", Parser = new[] { "DataTool.Flag.Converter", "CLIFlagBoolean" })]
can we simplify this to `no-update-check` 😊

2021-04-03 13:40 UTC, Js41637 commented on DataTool/Program.cs
> +
Not bad however could we change it to something like this
```cs
private static void CheckForUpdate() {
    try {
        Version localVersion = new Version(Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyFileVersionAttribute>()?.Version ?? string.Empty);
        if (Debugger.IsAttached || localVersion.Revision == 0) {
            return;
        }

        using (WebClient web = new WebClient()) {
            dynamic data = JObject.Parse(web.DownloadString(LastestBuildInfoUrl));
            Version remoteVersion = new Version(data.build.version.ToString());
            var buildSuccess = data.build.status == "success";

            if (remoteVersion > localVersion && buildSuccess) {
                Logger.Warn("Core", $"Newer version of DataTool is available! Local version: {localVersion} Latest: {remoteVersion}\nDownload latest build at {LastestBuildDownloadUrl}");
            }
        }
    } catch (Exception ex) {
        Logger.Debug("Core", $"Update check failed. {ex.Message}");
    }
}
```

2021-04-05 03:37 UTC, prophetl33t commented
So....... Is it okay?

2021-04-16 14:52 UTC, yretenai commented
So I have a problem with update checking without explicitly allowing it, but this is also one of the biggest issues the tool faces.

Donno, I'm uncomfortable with it.

2021-04-16 14:59 UTC, prophetl33t commented
We can set DisableUpdateCheck to true by default, but notify at startup that the user can enable update checking.

2021-04-16 15:03 UTC, prophetl33t commented
Or ask the user for permission to check the update if CASC fails.

2021-04-18 03:29 UTC, Js41637 commented
I don't think auto checking is a big deal, its just a single request when the tools have already failed. As long as there's a flag to disable it then i think it's ok.

I'd like to change where it checks for an update though, i've changed how the tools error when there is an unsupported version, we should move the update check there instead of here as this would check on just any random error. Having it only check when we know the tools don't support a game version would be better.

2021-08-17 10:41 UTC, closed without merging